### PR TITLE
Update UPS to Keycloak 1.7.0.Final

### PR DESCRIPTION
**Pull request by abstractj**
See: https://issues.jboss.org/browse/AGPUSH-1528

### CODE REVIEW

**Comment by matzew** [comment]
could we use 1.7.0.Final ?

**Comment by abstractj** [comment]
@matzew sure, sorry. Was my bad. updating it right now.

**Comment by abstractj** [comment]
@matzew done!

**Comment by matzew** [comment]
perfect, let me take a :eyes: here

**Pull request merged**
