### PR TITLE
Added Android libraries

### PR DESCRIPTION
**Pull request by danielpassos**
See: [AGDROID-714](https://issues.jboss.org/browse/AGDROID-714) - Move all aerogear-android-sdk dependencies to bom

### CODE REVIEW

**Comment by wtrocki** [comment]
@danielpassos Used temporary branch to test this. Green light from me to merge this change.
Question - do we need to create PR in aerogerar-android-sdk as well?

**Comment by danielpassos** [comment]
@wtrocki Yes we need, that is exactly what I did in the branch you have used to test, but I need to publish it on Maven Central first.

**Comment by danielpassos** [comment]
@pb82 I didn't but will do once got this merged.

**Comment by secondsun** [comment]
@danielpassos +1

**Pull request merged**
