### PR TITLE
[WIP] AGDROID-686 Add additional depenencies for auth module

### PR DESCRIPTION
**Pull request by aidenkeating**
Adding the `jose4j` dependency for the auth module in the SDK.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@danielpassos Would you mind taking a look? What's the best way to test this PR out in my SDK branch?

**Comment by danielpassos** [comment]
@aidenkeating `mvn clean install` in the root folder and change the [`build.gradle`](https://github.com/aerogear/aerogear-android-sdk/blob/master/build.gradle#L31) on AeroGear Android SDK to the [current snapshot version](https://github.com/aerogear/aerogear-parent/blob/master/pom.xml#L24)

**Comment by aidenkeating** [comment]
@danielpassos @matzew Do you have permissions to publish this properly?

**Comment by danielpassos** [comment]
I can do it for you!

**Comment by aidenkeating** [comment]
@danielpassos Thanks! 👍

**Pull request merged**
