### PR TITLE
Update with liquibase module

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by danielpassos** [comment]
@abstractj How I test this? build and run UPS using this?

**Comment by abstractj** [comment]
@danielpassos steps to test:

1. mvn clean install
2. get the changes here https://github.com/aerogear/aerogear-unifiedpush-server/pull/467
3. deploy the database file and the auth server

**Comment by matzew** [comment]
:+1: works fine on my machine (tm)

:tada:

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
Landed at 88f5c712c17863b8934d395e3681cb5ecc9ab28c

**Pull request closed without merging**
